language: node_js
# node version determined by .nvmrc
# default behavior is to `npm install` and `npm test`
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < lcov.info || echo "Could not upload code coverage to CodeClimate"
deploy:
  provider: heroku
  app: isocket-lennie
  api_key:
    secure: QID6aP091laC7v0FoafMrVpWkjucB31mjv4R+l+kxdVvHLb2QT8Z5vzxr9MHeqw0EFqA/cGHgpzd1CwTx/94oUeaJN7zVV+tDLuMTewMYf23IHHBjTCuzNCbpIQ/67FaCKGOWJH47Mo2zmenIZMjJDDuArgbNw/zKZ+lvewoMHo=
